#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# -------------------------------------------------------------------------- #
# Copyright 2010-2011, Hector Sanjuan, David Rodríguez, Pablo Donaire        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

$: << File.dirname(__FILE__)

require 'OneVBox'

#Restore receives a file. This file
#is a tar containing a domain_file
#and a VBox checkpoint.

#Steps:
#1 - untar
#2 - create vm and setup
#3 - adopt state with .sav file


checkpoint_tar = ARGV[0]
dir = File.dirname(checkpoint_tar)

domain_filename = `#{File.dirname(__FILE__)}/unpackState.sh #{checkpoint_tar}`.chomp
domain_filename = dir + "/" + domain_filename
rc = $?.exitstatus
exit rc if rc != 0


VM = OneVBox.new(nil,domain_filename)

rc = VM.create
rc = VM.modify unless rc
# rc = open_mediums if rc == 0 #deprecated Vbox 4.0
rc = VM.clone_disks unless rc
rc = VM.add_controllers unless rc
rc = VM.storage_attach unless rc
rc = VM.adopt_state("#{dir}/checkpoint.sav") unless rc
rc = VM.start unless rc

exit(rc) if rc
exit(0)
